name: Run CI Tests
on:
  push:
jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v -race ./...
